# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# XDG workarouds
export ZPLUG_HOME="$XDG_CONFIG_HOME/zsh/zplug"
export NVIM_LOG_FILE="$XDG_DATA_HOME/nvim/log"

# Common
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

# Language
export LANG='en_US.UTF-8'

# Terminal
export TERM='xterm-256color'

# Terminfo
export TERMINFO="$HOME/.config/terminfo"

# Programming specific
export GOPATH="$HOME/.go"

# Path
path=(
  /usr/local/{bin,sbin}
  $GOPATH/bin
  $CABALPATH/bin
  $path
)
